spring:
  cloud:
    config:
      failFast: true
      refreshInterval: 5000
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000
      discovery:
        enabled: true
        service-id: config-service
#      discovery:
#        service-id: config-server

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true