###--- RESOURCE-SERVICE ---

### POST non mp3 (non audio/mpeg)
POST http://localhost:8080/resource-service/resources
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Type: image/png
Content-Disposition: form-data; name="mp3"; filename="microservice_architecture_overview.png"

< ./statics/images/module1_basic_structure.png
--WebAppBoundary--

### POST mp3 (audio/mpeg) GATEWAY CALL
POST http://localhost:8080/resource-service/resources
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Type: audio/mpeg
Content-Disposition: form-data; name="mp3"; filename="valhalla_calling.mp3"

< ./statics/valhalla_calling.mp3
--WebAppBoundary--

### POST mp3 (audio/mpeg)
POST http://localhost:8080/resource-service/resources
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Type: audio/mpeg
Content-Disposition: form-data; name="mp3"; filename="valhalla_calling.mp3"

< ./statics/valhalla_calling.mp3
--WebAppBoundary--

### Get the binary audio data of a resource
GET http://localhost:8080/resource-service/resources/1

### Delete Resource by id (CSV string id's separated ',')
DELETE http://localhost:8080/resource-service/resources?id=1


### --- SONG-SERVICE ---

### POST mp3 file METADATA
POST http://localhost:8080/song-service/songs
Content-Type: application/json

{
  "resourceId": "3",
  "name": "We are the champions",
  "artist": "Queen",
  "album": "News of the world",
  "length": "2:59",
  "year": "1977"
}

### Get the metadata by id
GET http://localhost:8080/song-service/songs/2

### Delete metadata by id (CSV string id's separated ',')
DELETE http://localhost:8080/song-service/songs?id=2,4