### POST mp3 file METADATA
POST http://localhost:8182/songs
Content-Type: application/json

{
  "resourceId": "3",
  "name": "We are the champions",
  "artist": "Queen",
  "album": "News of the world",
  "length": "2:59",
  "year": "1977"
}

### Get the metadata by id
GET http://localhost:8182/songs/2

### Delete metadata by id (CSV string id's separated ',')
DELETE http://localhost:8182/songs?id=2,4
