version: "3.9"

services:
  ##### DATABASES required by services #####
  resource-service-db:
    image: postgres
    restart: always
    env_file:
      - ./local-config/resource-service.local.env
    expose: # allow access in docker network only (service not available from host)
      - 5432:5432
    ports: # allow access from host to services in docker (service available from host)
      - 5432:5432
    command: -p 5432
    networks:
      - spring-services-network

  song-service-db:
    image: postgres
    restart: always
    env_file:
      - ./local-config/song-service.local.env
    expose: # allow access in docker network only (service not available from host)
      - 5433:5433
    ports: # allow access from host to services in docker (service available from host)
      - 5433:5433
    command: -p 5433
    networks:
      - spring-services-network

  ##### AWS SERVICES EMULATION: S3 STORAGE #####
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main1}"
    image: localstack/localstack
    expose:
      - "4566:4566"
    ports:
      - "4510-4559:4510-4559"         # external services port range
      - "4566:4566"                   # LocalStack Gateway
      - "4572:4572"
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=s3,sqs,lambda,cloudformation,sts,iam,cloudwatch,apigateway,events
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DEBUG=1
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - AWS_BUCKET=localstack-s3-bucket
      - DEFAULT_REGION=us-east-1
    volumes:
      #- "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Initialization Hooks https://docs.localstack.cloud/references/init-hooks/
      - "./scripts/localstack/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh"
    networks:
      - spring-services-network

  ##### Messaging #####
  rabbitmq:
    image: rabbitmq:3.10.7-management
    restart: no
    ports:
      - "15672:15672"
      - "5672:5672"
    #  rabbitmq:
    #    image: rabbitmq:3-alpine
    #    container_name: "rabbitmq"
    #    ports:
    #      - 5672:5672
    #      - 15672:15672
    #    volumes:
    #      - ./rabbitmq/data/:/var/lib/rabbitmq/
    #      - ./rabbitmq/log/:/var/log/rabbitmq
    ##    networks:
    ##      - rabbitmq
    #    restart: unless-stopped
    networks:
      - spring-services-network

  ##### Infrastructure services #####
  discovery-service:
    image: jmp.microservices.fundamental/discovery-service:latest
    env_file:
      - ./local-config/discovery-service.local.env
    expose:
      - "8761:8761"
    ports:
      - "8761:8761"
    networks:
      - spring-services-network

  api-gateway-service:
    image: jmp.microservices.fundamental/api-gateway-service:latest
    env_file:
      - ./local-config/api-gateway-service.local.env
    expose:
      - "8888:8888"
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service

    networks:
      - spring-services-network

  ##### APPLICATION services #####
  resource-processor:
    image: jmp.microservices.fundamental/resource-processor:latest
    env_file:
      - ./local-config/resource-processor.local.env
    #    environment:
    #      SPRING_PROFILES_ACTIVE: "local"
    depends_on:
      - rabbitmq
    networks:
      - spring-services-network

  resource-service:
    image: jmp.microservices.fundamental/resource-service:latest
    env_file:
      - ./local-config/resource-service.local.env
    depends_on:
      - resource-service-db
      - localstack
      - rabbitmq
    expose:
      - "8181:8181"
    ports:
      - "8181:8181"
    networks:
      - spring-services-network

  song-service:
    image: jmp.microservices.fundamental/song-service:latest
    env_file:
      - ./local-config/song-service.local.env
    depends_on:
      - song-service-db
    expose:
      - "8182:8182"
    ports:
      - "8182:8182"
    networks:
      - spring-services-network

networks:
  spring-services-network:
    driver: bridge