version: "3.9"

services:
  ##### DATABASES required by services #####
  resource-service-db:
    image: postgres
    restart: always
    env_file:
      - ./local-config/resource-service.local.env
    expose: # allow access in docker network only (service not available from host)
      - 5432:5432
    ports: # allow access from host to services in docker (service available from host)
      - 5432:5432
    command: -p 5432
    networks:
      - spring-services-network

  song-service-db:
    image: postgres
    restart: always
    env_file:
      - ./local-config/song-service.local.env
    expose: # allow access in docker network only (service not available from host)
      - 5433:5433
    ports: # allow access from host to services in docker (service available from host)
      - 5433:5433
    command: -p 5433
    networks:
      - spring-services-network

  ##### AWS SERVICES EMULATION: S3 STORAGE #####
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main1}"
    image: localstack/localstack
    ports:
      - "4510-4559:4510-4559"         # external services port range
      - "4566:4566"                   # LocalStack Gateway
      - "4572:4572"
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=s3,sqs,lambda,cloudformation,sts,iam,cloudwatch,apigateway,events
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DEBUG=1
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - DEFAULT_REGION=us-east-1
    volumes:
      #- "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Initialization Hooks https://docs.localstack.cloud/references/init-hooks/
      - "./scripts/localstack/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh"
    networks:
      - spring-services-network

  ##### APPLICATION services #####


networks:
  spring-services-network:
    driver: bridge