server:
  port: 8761
spring:
  application:
    name: eureka-discovery-service
  banner:
    location: classpath:banner.txt

eureka:
  dashboard:
    path: /eureka-dashboard
    enabled: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: info,health
      cors:
        allowed-methods: GET,PUT,POST,OPTIONS
        allowed-headers: origin,content-type,accept,clientinfo.clientid,clientinfo.instanceid,clientinfo.originip,clientinfo.version,securitytoken,clientinfo.domainversion,clientinfo.frameworkversion,clientinfo.instancetag,clientinfo.locale,clientinfo.operatingsystemname,clientinfo.runtimename,clientinfo.runtimeversion,clientinfo.timezone,correlationid,id
        allow-credentials: true
    enabled-by-default: true