server:
  port: 0

spring:
  datasource:
    url: ${SONG_POSTGRES_URL}
    username: song
    password: s3cr3t

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  instance:
    instanceId: ${spring.profiles.active:default}-${spring.application.name}-id${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: info,health
